# Generated by Django 4.1.1 on 2022-09-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titule', models.CharField(max_length=100)),
                ('module', models.TextField()),
                ('students', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
